# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armed', models.TextField(blank=True, max_length=500, verbose_name='Details about whether the deceased was armed')),
                ('charges', models.TextField(blank=True, max_length=500, verbose_name='Details about the charges or conviction')),
                ('mental_health', models.TextField(blank=True, max_length=500, verbose_name='Detailed mental health information')),
                ('classification', models.TextField(blank=True, max_length=500, verbose_name='Details about the classification of the death')),
                ('media_source', models.URLField(blank=True, max_length=500, verbose_name='Urls of media media_source')),
                ('image_of', models.URLField(blank=True, max_length=500, verbose_name='Url of an image of the deceased')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Expanded address the event occured at')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Long form description of the event')),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Full Name')),
                ('age', models.IntegerField(db_index=True, verbose_name='Age')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('u', 'Unknown')], db_index=True, default='u', max_length=1, verbose_name='Gender')),
                ('race', models.CharField(choices=[('i', 'Indigenous'), ('b', 'Black'), ('w', 'White'), ('wa', 'Arab/West Asian'), ('n', 'Asian'), ('sa', 'South Asian'), ('m', 'Mixed Race'), ('se', 'Southeast Asian'), ('l', 'Latin American'), ('o', 'Other'), ('u', 'Unknown')], db_index=True, default='u', max_length=2, verbose_name='Race/Ethnicity')),
                ('armed', models.CharField(choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], db_index=True, default='u', max_length=1, verbose_name='Was the deceased armed?')),
                ('charges', models.CharField(choices=[('n', 'No Charges'), ('l', 'Charges Laid'), ('c', 'Conviction'), ('i', 'Under Investigation'), ('u', 'Unknown')], db_index=True, default='u', max_length=1, verbose_name='Status of charges or conviction')),
                ('classification', models.CharField(choices=[('g', 'Gunshot'), ('o', 'Other'), ('c', 'CEW'), ('u', 'Unknown')], db_index=True, default='u', max_length=1, verbose_name='Status of charges or conviction')),
                ('alleged_suicide', models.BooleanField(db_index=True, verbose_name='Was the death an alleged suicide?')),
                ('mental_health', models.BooleanField(db_index=True, verbose_name='Was there an indication of mental health barriers or distress?')),
                ('postal_code', models.CharField(blank=True, max_length=6, verbose_name='Postal Code')),
                ('latitude', models.FloatField(blank=True, db_index=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, db_index=True, verbose_name='Longitude')),
                ('submitted_by', models.CharField(blank=True, max_length=150, verbose_name='Submitted by')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Submission date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Updated date')),
                ('occured_date', models.DateField(db_index=True, verbose_name='Occured date')),
                ('needs_review', models.BooleanField(db_index=True, verbose_name='Needs Review')),
                ('details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details_from', to='thereported.Details')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceDepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Name')),
                ('city', models.CharField(db_index=True, max_length=200, verbose_name='City, town, or jurisdiction')),
                ('province', models.CharField(choices=[('PE', 'PEI'), ('ON', 'Ontario'), ('QC', 'Quebec'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('SK', 'Saskatchewan'), ('YT', 'Yukon Territor')], db_index=True, default='PE', max_length=2, verbose_name='Province')),
                ('investigating', models.CharField(db_index=True, max_length=500, verbose_name='investigating body')),
            ],
        ),
        migrations.AddField(
            model_name='incidents',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_dept_of', to='thereported.PoliceDepts'),
        ),
    ]
