# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thereported', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armed', models.TextField(blank=True, max_length=500, verbose_name='Details about whether the deceased was armed')),
                ('charges', models.TextField(blank=True, max_length=500, verbose_name='Details about the charges or conviction')),
                ('mental_health', models.TextField(blank=True, max_length=500, verbose_name='Detailed mental health information')),
                ('classification', models.TextField(blank=True, max_length=500, verbose_name='Details about the classification of the death')),
                ('media_source', models.URLField(blank=True, max_length=500, verbose_name='Urls of media source')),
                ('image_of', models.URLField(blank=True, max_length=500, verbose_name='Url of an image of the deceased')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Expanded address the event occured at')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Long form description of the event')),
            ],
        ),
        migrations.RenameModel(
            old_name='Incidents',
            new_name='Incident',
        ),
        migrations.RenameModel(
            old_name='PoliceDepts',
            new_name='PoliceDept',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AlterField(
            model_name='incident',
            name='details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details_from', to='thereported.Detail'),
        ),
    ]
