# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Movie location')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('length', models.DurationField(verbose_name='Length of movie')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=3000, verbose_name='Review')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Published date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Updated date')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movietracker.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_date', models.DateField(auto_now_add=True, verbose_name='Watched date')),
                ('started_watching', models.TimeField(auto_now_add=True, verbose_name='Began watching')),
                ('finished_watching', models.TimeField(auto_now=True, verbose_name='Stopped watching')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movietracker.Movie')),
            ],
        ),
    ]
