# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietracker', '0003_auto_20161211_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
    ]
