# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietracker', '0004_remove_movie_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewed',
            name='finished_watching',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_id',
            field=models.CharField(default='ZvVJx7dcoqo', max_length=10, verbose_name='Video id'),
            preserve_default=False,
        ),
    ]
